
server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2


